GET http://localhost:8080/posts
Accept: application/json
Cache-Control: no-cache
Authorization: Basic VXNlcjI6ZGhhczlkOGhkcTJkZQ==

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("The question contains 4 posts", function() {
        client.assert(response.body.length === 4, "Expected 3 answers");
    });
%}

###

GET http://localhost:8080/posts/1
Accept: application/json
Cache-Control: no-cache
Authorization: Basic VXNlcjI6ZGhhczlkOGhkcTJkZQ==

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("The question contains 3 answers", function() {
        client.assert(response.body.answers.length === 3, "Expected 3 answers");
    });
%}



###